permalink   : /:title/
markdown    : kramdown
highlighter : pygments

paginate: 3 #6
comments: true
paginate_path: "/page/:num"

baseurl: ""
domain_name: blog.brianmkelley.com
google_analytics: UA-22893252-3

source:      source
destination: _site

# cover: /assets/images/header-cover.png

# site title, description, meta_description, meta_keywords
# Details for the RSS feed generator
name: Brian Kelley
title: Brian Kelley | DevOps Engineer
description: "DevOps Engineer, Docker enthusiast, programming dabbler"
meta_description: ""
meta_keywords: "site, website, docker, artifactory, bamboo, atlassian, stash, bitbucket, jira"
url: http://blog.brianmkelley.com
production_url: http://blog.brianmkelley.com
repo: https://github.com/battlecow/battlecow.github.io
disqus_shortname: "briankelley"
rss_path: source/
author:
  name      : Brian Kelley
  image     : /assets/images/author.jpg
  email     : bmk352@gmail.com
  url       : https://blog.brianmkelley.com
  twitter   : https://twitter.com/bmk352
  github    : http://github.com/battlecow
  bio       : "DevOps Engineer"

# Plugin: jekyll-assets
assets:
  dirname: /assets
  baseurl: /assets/ # change to /assets/
  sources:
    - assets/images
    - assets/fonts
    - assets/css
    - assets/js
  cache: true
  gzip: [ text/css, application/javascript ]

# Compress HTML
compress_html:
  clippings: all
  comments: all
  endings: all
  profile: false
  ignore:
    envs: all
exclude: ["gulp", "node_modules", "bower", "bower_components", "config.rb", "src", "Gemfile", "Gemfile.lock", ".rvmrc", ".rbenv-version", "package.json", "gulpfile.js", "README.md", "Rakefile", "changelog.md"]

#gems: [jekyll-responsive_image]
responsive_image:
  template: source/_includes/responsive-image.html
  default_quality: 90
  sizes:
    - width: 480  # [Required] How wide the resized image will be.
      quality: 80 # [Optional] Overrides default_quality for this size.
    - width: 800
    - width: 1400
      quality: 90
  base_path: source/assets/images
  output_path_format: source/assets/images/resized/%{width}/%{basename}